version: '3.5'

services:
  rabbitmq_client:
    build: .
    container_name: rabbitmq_client
    volumes:
      - .:/var/www/html
    ports:
      - 8090:80
    tty: true
    restart: always
    networks:
      - net1
networks:
  net1:
    name: net1
    driver: bridge
    internal: false
    ipam:
      driver: default
      config: 
        - subnet: 100.127.255.0/24