version: '3.5'

services:
  rabbitmq_client:
    build: .
    container_name: rabbitmq_client
    volumes:
      - .:/var/www/html/sites/default/files
    ports:
      - 8091:80
    env_file:
      - .env
    tty: true
    restart: always
    networks:
      - net1
networks:
  net1:
    driver: bridge
    internal: false
    ipam:
      driver: default
      config: 
        - subnet: 100.127.255.0/24